#si può anche valutare eliminazione che crea solo caos
# Step 1: Build app with Vite
FROM node:20 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build

# Step 2: Serve with nginx
FROM nginx:alpine

# Copy built files
COPY --from=builder /app/dist /usr/share/nginx/html

# Replace nginx default config to support SPA routing
COPY nginx.conf /etc/nginx/conf.d/default.conf  

# Expose port 8080 for Cloud Run
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]