services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8081:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/firebase-service-account.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-service-account.json
