swagger: "2.0"
info:
  title: Backend API
  version: 1.0.0

schemes:
  - https

paths:
  /anonymize:
    options:
      summary: CORS support
      operationId: corsAnonymize
      security: []
      responses:
        '204':
          description: CORS preflight support
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: "http://localhost:8080"
            Access-Control-Allow-Methods:
              type: string
              default: "POST, OPTIONS"
            Access-Control-Allow-Headers:
              type: string
              default: "Authorization, Content-Type"
    post:
      summary: Anonimizza dati
      operationId: anonymizeData
      x-google-backend:
        address: https://backend-service-583549727222.europe-west1.run.app
        protocol: h2
      security:
        - firebase: []
      responses:
        '200':
          description: Success


securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/gruppo-5"
    #x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/gateway-sa@gruppo-5.iam.gserviceaccount.com"
    x-google-audiences: "gruppo-5"
    x-google-endpoints:
      - name: backend-gateway-7g2ufv92.ew.gateway.dev
        allowCors: true
