swagger: "2.0"
info:
  title: Backend API
  version: 1.0.0

host: backend-gateway-7g2ufv92.ew.gateway.dev
schemes:
  - https

paths:
  /anonymize:
    options:
      summary: CORS pre-flight
      operationId: corsAnonymize
      security: []                  # niente JWT sul pre-flight
      responses:
        '204':
          description: Ok
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: http://localhost:8080
            Access-Control-Allow-Methods:
              type: string
              default: "POST, OPTIONS"
            Access-Control-Allow-Headers:
              type: string
              default: "Authorization, Content-Type"
    post:
      summary: Anonimizza dati
      operationId: anonymizeData
      x-google-backend:
        address: https://backend-service-583549727222.europe-west1.run.app
        protocol: h2
        jwt_audience: https://backend-service-583549727222.europe-west1.run.app
      security:
        - firebase: []
      responses:
        '200':
          description: Success

securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/gruppo-5"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
    x-google-audiences: "gruppo-5"

security:
  - firebase: []

x-google-endpoints:
  - name: backend-gateway-7g2ufv92.ew.gateway.dev
